name: Delete cf-deploy Workflow Runs

on:
  workflow_run:
    workflows: ["Deploy Cloudflare Workers", "AI Code Review"] # Names of the workflows to monitor
    types:
      - completed

jobs:
  delete_run:
    runs-on: ubuntu-latest
    permissions:
      actions: write # Required permission to delete workflow runs
    steps:
      - name: Get workflow run details
        id: get_run_details
        run: |
          echo "Workflow run event received for workflow: ${{ github.event.workflow_run.name }}"
          echo "Workflow run ID: ${{ github.event.workflow_run.id }}"
          echo "Workflow run conclusion: ${{ github.event.workflow_run.conclusion }}"
          echo "Workflow run URL: ${{ github.event.workflow_run.url }}"
          echo "run_id=${{ github.event.workflow_run.id }}" >> $GITHUB_OUTPUT

      - name: Delete the completed workflow run
        if: ${{ github.event.workflow_run.conclusion == 'success' || github.event.workflow_run.conclusion == 'failure' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OWNER: ${{ github.repository_owner }}
          REPO: ${{ github.event.repository.name }}
          RUN_ID: ${{ steps.get_run_details.outputs.run_id }}
        run: |
          echo "Attempting to delete workflow run ID: $RUN_ID for workflow ${{ github.event.workflow_run.name }}"
          curl -X DELETE \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer $GITHUB_TOKEN" \
            https://api.github.com/repos/$OWNER/$REPO/actions/runs/$RUN_ID
          echo "Workflow run deletion request sent."